# Generated by Django 3.2.8 on 2021-10-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0002_auto_20211016_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_venda', models.CharField(auto_created=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxr.cliente')),
                ('veiculo', models.ManyToManyField(blank=True, null=True, to='rxr.Veiculos')),
            ],
        ),
    ]
