# Generated by Django 3.2.8 on 2021-10-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0004_remove_venda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='venda',
            name='veiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rxr.veiculos'),
        ),
    ]
