# Generated by Django 3.2.8 on 2021-10-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0005_auto_20211016_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='numero_da_venda',
        ),
    ]
