# Generated by Django 3.2.8 on 2021-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0007_remove_venda_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='preco_extenco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Preço Por Extenso'),
        ),
    ]
