# Generated by Django 3.2.8 on 2021-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0009_venda_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
