# Generated by Django 3.2.8 on 2021-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0010_alter_cliente_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
