# Generated by Django 3.2.8 on 2021-10-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxr', '0011_venda_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
